#!/bin/bash
if [ "$EUID" -ne 0 ]; then
    echo "Run $0 as root to complete install." > /dev/stderr
    exit 0
fi

set -ex

CP_A="cp -afv"
LN_S="ln -fsv"
MKDIR_P="mkdir -pv"
SYNOPKG_PKGDEST=/var/packages/zfs/target
SMBCONF=/etc/samba/smb.conf

$MKDIR_P /etc/default /etc/exports.d

$CP_A --preserve=links $SYNOPKG_PKGDEST/usr/lib/systemd/system/* /usr/lib/systemd/system/

for m in $(find $SYNOPKG_PKGDEST/lib/modules -type f); do
    $LN_S $m /lib/modules/asd
done

$LN_S $SYNOPKG_PKGDEST/etc/default/* /etc/default/
$LN_S $SYNOPKG_PKGDEST/lib/udev/*_id /lib/udev/
$LN_S $SYNOPKG_PKGDEST/lib/udev/rules.d/* /lib/udev/rules.d/
$LN_S $SYNOPKG_PKGDEST/sbin/mount.zfs /sbin/
$LN_S $SYNOPKG_PKGDEST/etc/zfs /etc/
$LN_S $SYNOPKG_PKGDEST/usr/lib/lib* /usr/lib/
$LN_S $SYNOPKG_PKGDEST/usr/libexec/zfs /usr/libexec/
$LN_S $SYNOPKG_PKGDEST/usr/sbin/* /usr/sbin/

chown -c root:root /{etc,usr/libexec}/zfs/zed.d/*

systemctl enable pkg-zfs-load-spl-ko.service pkg-zfs-load-zfs-ko.service zfs-import-scan.service $(awk '/^enable/ { print $2 }' < $SYNOPKG_PKGDEST/usr/lib/systemd/system-preset/*)

# Workaround for zfs not supporting syno_recvfile
# https://github.com/jberkman/synozfs/issues/4
if [ -s ${SMBCONF} ] && ! grep -q "min receivefile size" ${SMBCONF}
    printf '\tmin receivefile size = 0\n' >> ${SMBCONF}
    killall -HUP smbd
fi
